name: Release

on:
  push:
    tags:
      - 'v*' 

env:
    REGISTRY: ghcr.io

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set branch name
        id: branch
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF:11} | tr / -)

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' 

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build CLI with version
        run: |
          echo "${{ steps.version.outputs.version }}" > version
          go build -o netsocs .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          body: "Automated release for version ${{ steps.version.outputs.version }}"
          files: |
            netsocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}